<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CoffeeSeeder extends Seeder
{
    public function run(): void
    {
        $coffees = [
            [
                'coffee_name'    => 'Espresso',
                'coffee_image'   => 'coffees/espresso.jpg',
                'description'    => 'Espresso is a rich, bold, and concentrated coffee beverage brewed by forcing hot water under high pressure through finely-ground coffee beans. It serves as the foundation for many coffee drinks such as lattes, cappuccinos, and macchiatos. Known for its thick crema and intense aroma, espresso delivers a deep flavour that coffee purists adore.',
                'ingredients'    => 'Water, Coffee Beans',
                'coffee_type'    => 'strong',
                'lactose'        => 'no',
                'minimum_price'  => 80.00,
                'maximum_price'  => 110.00,
                'rating'         => 4.5,
                'likes'          => 120,
                'favorites'      => 25,
            ],
            [
                'coffee_name'    => 'Cappuccino',
                'coffee_image'   => 'coffees/cappuccino.jpg',
                'description'    => 'A cappuccino is a classic Italian coffee drink made with equal parts espresso, steamed milk, and milk foam. The result is a smooth, velvety texture with a perfect balance of rich espresso and creamy milk. Often topped with cocoa powder or cinnamon, cappuccino offers a cozy and indulgent coffee experience.',
                'ingredients'    => 'Espresso, Steamed Milk, Milk Foam',
                'coffee_type'    => 'strong',
                'lactose'        => 'yes',
                'minimum_price'  => 120.00,
                'maximum_price'  => 150.00,
                'rating'         => 4.7,
                'likes'          => 200,
                'favorites'      => 60,
            ],
            [
                'coffee_name'    => 'Latte',
                'coffee_image'   => 'coffees/latte.png',
                'description'    => 'A latte is a smooth and creamy espresso-based coffee made with a generous amount of steamed milk and a light layer of foam on top. It has a milder taste compared to espresso or cappuccino, making it perfect for those who enjoy a softer, milk-forward coffee flavour. You can enjoy it plain or with flavored syrups like vanilla or caramel.',
                'ingredients'    => 'Espresso, Steamed Milk',
                'coffee_type'    => 'strong',
                'lactose'        => 'yes',
                'minimum_price'  => 110.00,
                'maximum_price'  => 150.00,
                'rating'         => 4.6,
                'likes'          => 180,
                'favorites'      => 40,
            ],
            [
                'coffee_name'    => 'Cold Brew',
                'coffee_image'   => 'coffees/coldbrew.png',
                'description'    => 'Cold brew is a refreshing coffee made by steeping coarsely ground coffee beans in cold water for 12–24 hours. This slow extraction process produces a smooth, less acidic coffee with natural sweetness and chocolatey undertones. Served over ice, it’s the perfect choice for a hot day or a caffeine boost without bitterness.',
                'ingredients'    => 'Cold Water, Coffee Beans',
                'coffee_type'    => 'strong',
                'lactose'        => 'no',
                'minimum_price'  => 150.00,
                'maximum_price'  => 170.00,
                'rating'         => 4.3,
                'likes'          => 95,
                'favorites'      => 30,
            ],
            [
                'coffee_name'    => 'Iced Matcha',
                'coffee_image'   => 'coffees/icedmatcha.webp',
                'description'    => 'Iced Matcha is a refreshing and vibrant green tea drink made from finely ground Japanese matcha powder whisked with milk and poured over ice. It offers a perfect blend of earthy tea flavour, creamy texture, and subtle sweetness, providing a calm, energizing experience without the jitters of coffee.',
                'ingredients'    => 'Matcha Powder, Cold Milk, Ice, Sweetener',
                'coffee_type'    => 'balanced',
                'lactose'        => 'yes',
                'minimum_price'  => 140.00,
                'maximum_price'  => 170.00,
                'rating'         => 4.8,
                'likes'          => 220,
                'favorites'      => 80,
            ],
            [
                'coffee_name'    => 'Spanish Latte',
                'coffee_image'   => 'coffees/spanish_latte.jpg',
                'description'    => 'Spanish Latte is a creamy and indulgent coffee drink that combines rich espresso with steamed milk and sweetened condensed milk. The result is a perfectly balanced beverage with deep espresso notes complemented by luscious sweetness and silky texture — a true treat for those who love sweet, milky coffees.',
                'ingredients'    => 'Espresso, Steamed Milk, Sweetened Condensed Milk',
                'coffee_type'    => 'balanced',
                'lactose'        => 'yes',
                'minimum_price'  => 120.00,
                'maximum_price'  => 150.00,
                'rating'         => 4.7,
                'likes'          => 95,
                'favorites'      => 15,
            ],
            [
                'coffee_name'    => 'Macchiato',
                'coffee_image'   => 'coffees/macchiato.jpg',
                'description'    => 'Macchiato, which means "stained" or "spotted" in Italian, is a shot of espresso lightly topped with a small amount of milk foam. This drink retains the boldness of espresso while softening its intensity just slightly, making it a popular choice for those who appreciate a strong yet refined coffee experience.',
                'ingredients'    => 'Espresso, Milk Foam',
                'coffee_type'    => 'balanced',
                'lactose'        => 'yes',
                'minimum_price'  => 100.00,
                'maximum_price'  => 130.00,
                'rating'         => 4.3,
                'likes'          => 85,
                'favorites'      => 20,
            ],
            [
                'coffee_name'    => 'Affogato',
                'coffee_image'   => 'coffees/affogato.jpg',
                'description'    => 'Affogato is an Italian dessert-coffee hybrid made by pouring a hot shot of espresso over a scoop of vanilla ice cream. The contrast between the bitter espresso and the creamy, sweet ice cream creates a heavenly balance of flavours and textures — warm and cold, bold and sweet — perfect as an after-meal indulgence.',
                'ingredients'    => 'Espresso, Vanilla Ice Cream',
                'coffee_type'    => 'sweet',
                'lactose'        => 'yes',
                'minimum_price'  => 130.00,
                'maximum_price'  => 160.00,
                'rating'         => 4.6,
                'likes'          => 90,
                'favorites'      => 30,
            ],
            [
                'coffee_name'    => 'Americano',
                'coffee_image'   => 'coffees/americano.jpg',
                'description'    => 'Americano is a smooth and classic coffee drink made by diluting espresso with hot water, creating a lighter body and milder flavour without losing the espresso’s depth. It’s a perfect choice for coffee lovers who prefer a clean, straightforward cup with a rich aroma and balanced acidity.',
                'ingredients'    => 'Espresso, Hot Water',
                'coffee_type'    => 'strong',
                'lactose'        => 'no',
                'minimum_price'  => 90.00,
                'maximum_price'  => 120.00,
                'rating'         => 4.4,
                'likes'          => 110,
                'favorites'      => 50,
            ],
            [
                'coffee_name'    => 'Ristretto',
                'coffee_image'   => 'coffees/ristretto.jpg',
                'description'    => 'Ristretto is a short shot of espresso made with the same amount of coffee grounds but half the water. This results in a thicker, more concentrated brew with an intense, syrupy flavour and slightly sweeter notes. It’s a bold, full-bodied coffee for those who love an intense caffeine kick.',
                'ingredients'    => 'Espresso',
                'coffee_type'    => 'strong',
                'lactose'        => 'no',
                'minimum_price'  => 90.00,
                'maximum_price'  => 120.00,
                'rating'         => 4.7,
                'likes'          => 220,
                'favorites'      => 90,
            ],
            [
                'coffee_name'    => 'Long Black',
                'coffee_image'   => 'coffees/long_black.jpg',
                'description'    => 'A Long Black is made by pouring a double shot of espresso over hot water, preserving the crema on top and offering a bold yet aromatic cup. It’s similar to an Americano but with more intensity and depth, providing a robust coffee experience for those who enjoy strong, black coffee without dilution.',
                'ingredients'    => 'Espresso, Hot Water',
                'coffee_type'    => 'strong',
                'lactose'        => 'no',
                'minimum_price'  => 85.00,
                'maximum_price'  => 110.00,
                'rating'         => 3.1,
                'likes'          => 55,
                'favorites'      => 20,
            ],
            [
                'coffee_name'    => 'Kapeng Barako',
                'coffee_image'   => 'coffees/kapeng_barako.png',
                'description'    => 'Kapeng Barako is a bold and aromatic Filipino coffee made from Liberica beans, known for their strong, smoky, and slightly fruity flavour profile. It’s a traditional favorite in Batangas and other provinces, often brewed black to showcase its full-bodied taste. Kapeng Barako stands as a symbol of Filipino coffee culture and pride.',
                'ingredients'    => 'Liberica Coffee Beans, Hot Water',
                'coffee_type'    => 'strong',
                'lactose'        => 'no',
                'minimum_price'  => 80.00,
                'maximum_price'  => 110.00,
                'rating'         => 4.9,
                'likes'          => 310,
                'favorites'      => 120,
            ],
            [
                'coffee_name'    => 'Flat White',
                'coffee_image'   => 'coffees/flat_white.jpg',
                'description'    => 'The Flat White is a smooth and velvety espresso-based drink made with micro-foamed milk. It offers the perfect harmony between strong espresso flavour and creamy milk texture, making it a favourite for those who love a rich, full-bodied coffee without excessive froth. Originating from Australia and New Zealand, it has become a modern café classic.',
                'ingredients'    => 'Espresso, Steamed Milk',
                'coffee_type'    => 'strong',
                'lactose'        => 'yes',
                'minimum_price'  => 100.00,
                'maximum_price'  => 140.00,
                'rating'         => 4.3,
                'likes'          => 150,
                'favorites'      => 60,
            ],
            [
                'coffee_name'    => 'Cortado',
                'coffee_image'   => 'coffees/cortado.jpg',
                'description'    => 'The Cortado is a balanced espresso beverage that combines equal parts espresso and warm milk. Originating from Spain, it’s designed to cut the acidity of espresso while maintaining its bold character. The result is a silky, rich, and perfectly proportioned drink that highlights both coffee and milk in harmony.',
                'ingredients'    => 'Espresso, Warm Milk',
                'coffee_type'    => 'strong',
                'lactose'        => 'yes',
                'minimum_price'  => 95.00,
                'maximum_price'  => 130.00,
                'rating'         => 2.7,
                'likes'          => 30,
                'favorites'      => 10,
            ],
            [
                'coffee_name'    => 'Bulletproof Coffee',
                'coffee_image'   => 'coffees/bulletproof_coffee.jpg',
                'description'    => 'Bulletproof Coffee is a unique blend of freshly brewed coffee, unsalted butter, and MCT oil, whipped together for a creamy, frothy texture. Popular among keto enthusiasts, this drink provides sustained energy and mental clarity without sugar crashes. It’s both indulgent and functional — coffee that fuels your body and mind.',
                'ingredients'    => 'Coffee, Butter, MCT Oil',
                'coffee_type'    => 'strong',
                'lactose'        => 'yes',
                'minimum_price'  => 110.00,
                'maximum_price'  => 160.00,
                'rating'         => 2.5,
                'likes'          => 20,
                'favorites'      => 7,
            ],
            [
                'coffee_name'    => 'Mocha',
                'coffee_image'   => 'coffees/mocha.jpg',
                'description'    => 'Mocha is a delightful combination of espresso, steamed milk, and chocolate syrup, often topped with whipped cream or cocoa powder. This drink brings together the richness of coffee and the sweetness of chocolate for a comforting, dessert‑like experience. It’s perfect for anyone who loves coffee with a sweet twist.',
                'ingredients'    => 'Espresso, Chocolate Syrup, Steamed Milk',
                'coffee_type'    => 'strong',
                'lactose'        => 'yes',
                'minimum_price'  => 120.00,
                'maximum_price'  => 160.00,
                'rating'         => 4.8,
                'likes'          => 290,
                'favorites'      => 110,
            ],
            [
                'coffee_name'    => 'Red Eye Coffee',
                'coffee_image'   => 'coffees/red_eye_coffee.jpg',
                'description'    => 'Red Eye Coffee is a bold and highly caffeinated beverage that combines brewed drip coffee with a shot of espresso. It delivers an intense flavour and an extra energy kick, making it a go-to drink for late nights, early mornings, or anyone needing serious focus and alertness.',
                'ingredients'    => 'Drip Coffee, Espresso',
                'coffee_type'    => 'strong',
                'lactose'        => 'no',
                'minimum_price'  => 95.00,
                'maximum_price'  => 140.00,
                'rating'         => 2.9,
                'likes'          => 28,
                'favorites'      => 8,
            ],
            [
                'coffee_name'    => 'Dirty Chai Latte',
                'coffee_image'   => 'coffees/dirty_chai_latte.jpg',
                'description'    => 'Dirty Chai Latte is a flavorful fusion of spiced chai tea and espresso, topped with steamed milk for a creamy finish. It’s a perfect blend of aromatic spices and bold coffee, creating a cozy yet invigorating drink that awakens the senses. Ideal for those who enjoy both tea and coffee in one cup.',
                'ingredients'    => 'Espresso, Chai Tea, Steamed Milk',
                'coffee_type'    => 'strong',
                'lactose'        => 'yes',
                'minimum_price'  => 130.00,
                'maximum_price'  => 170.00,
                'rating'         => 4.4,
                'likes'          => 180,
                'favorites'      => 70,
            ],
            [
                'coffee_name'    => 'Vienna Coffee',
                'coffee_image'   => 'coffees/vienna_coffee.jpg',
                'description'    => 'Vienna Coffee is a classic European beverage made with two shots of espresso topped with a generous layer of whipped cream. The cream slowly melts into the espresso, balancing its strong flavour with sweetness and richness. It’s elegant, comforting, and perfect for savoring during quiet moments.',
                'ingredients'    => 'Espresso, Whipped Cream',
                'coffee_type'    => 'strong',
                'lactose'        => 'yes',
                'minimum_price'  => 110.00,
                'maximum_price'  => 150.00,
                'rating'         => 3.5,
                'likes'          => 80,
                'favorites'      => 30,
            ],
            [
                'coffee_name'    => 'Espresso con Panna',
                'coffee_image'   => 'coffees/espresso_con_panna.jpg',
                'description'    => 'Espresso con Panna is a simple yet luxurious drink featuring a rich shot of espresso topped with a dollop of whipped cream. The cream adds a smooth, sweet contrast to the espresso’s boldness, making every sip indulgent and satisfying — a true treat for espresso lovers with a sweet tooth.',
                'ingredients'    => 'Espresso, Whipped Cream',
                'coffee_type'    => 'strong',
                'lactose'        => 'yes',
                'minimum_price'  => 100.00,
                'maximum_price'  => 140.00,
                'rating'         => 2.6,
                'likes'          => 24,
                'favorites'      => 9,
            ],
            [
                'coffee_name'    => 'Cafe Latte',
                'coffee_image'   => 'coffees/cafe_latte.jpg',
                'description'    => 'Cafe Latte is a comforting and creamy coffee drink made with espresso and steamed milk, finished with a light layer of foam. It has a mellow, silky flavour that’s perfect for those who prefer a smooth and balanced coffee experience. Often served in large cups, it’s great for slow mornings and relaxing afternoons.',
                'ingredients'    => 'Espresso, Steamed Milk',
                'coffee_type'    => 'balanced',
                'lactose'        => 'yes',
                'minimum_price'  => 110.00,
                'maximum_price'  => 150.00,
                'rating'         => 4.6,
                'likes'          => 200,
                'favorites'      => 90,
            ],
            [
                'coffee_name'    => 'Cafe au Lait',
                'coffee_image'   => 'coffees/cafe_au_lait.jpg',
                'description'    => 'Cafe au Lait is a French-style coffee that blends brewed coffee with steamed milk in equal proportions. Its mild flavour and creamy texture make it a comforting choice for any time of the day. It’s simple, smooth, and elegant — the essence of relaxed European coffee culture.',
                'ingredients'    => 'Brewed Coffee, Steamed Milk',
                'coffee_type'    => 'balanced',
                'lactose'        => 'yes',
                'minimum_price'  => 100.00,
                'maximum_price'  => 130.00,
                'rating'         => 3.0,
                'likes'          => 60,
                'favorites'      => 22,
            ],
            [
                'coffee_name'    => 'Brown Sugar Latte',
                'coffee_image'   => 'coffees/brown_sugar_latte.jpg',
                'description'    => 'Brown Sugar Latte is a deliciously sweet and aromatic drink made with espresso, steamed milk, and caramelized brown sugar syrup. The deep molasses flavour of the brown sugar pairs beautifully with the coffee’s richness, creating a smooth, cozy, and slightly smoky taste that feels like a warm hug in a cup.',
                'ingredients'    => 'Espresso, Steamed Milk, Brown Sugar Syrup',
                'coffee_type'    => 'balanced',
                'lactose'        => 'yes',
                'minimum_price'  => 120.00,
                'maximum_price'  => 160.00,
                'rating'         => 4.7,
                'likes'          => 240,
                'favorites'      => 95,
            ],
            [
                'coffee_name'    => 'Breve Coffee',
                'coffee_image'   => 'coffees/breve_coffee.jpg',
                'description'    => 'Breve Coffee is a rich and creamy espresso drink made with half‑and‑half instead of milk. The extra creaminess gives it a luxurious mouthfeel and slightly sweet flavour, making it a satisfying option for those who love indulgent coffee experiences. It’s like a latte, but thicker, richer, and absolutely delightful.',
                'ingredients'    => 'Espresso, Half‑and‑Half',
                'coffee_type'    => 'balanced',
                'lactose'        => 'yes',
                'minimum_price'  => 130.00,
                'maximum_price'  => 170.00,
                'rating'         => 2.8,
                'likes'          => 32,
                'favorites'      => 12,
            ],
            [
                'coffee_name'    => 'Vanilla Latte',
                'coffee_image'   => 'coffees/vanilla_latte.jpg',
                'description'    => 'A timeless favourite that blends smooth espresso with steamed milk and a touch of vanilla syrup. This creamy latte delivers a comforting balance of sweetness and aroma, perfect for a cozy coffee break any time of the day.',
                'ingredients'    => 'Espresso, Steamed Milk, Vanilla Syrup',
                'coffee_type'    => 'balanced',
                'lactose'        => 'yes',
                'minimum_price'  => 120.00,
                'maximum_price'  => 160.00,
                'rating'         => 4.8,
                'likes'          => 270,
                'favorites'      => 100,
            ],
            [
                'coffee_name'    => 'Drip Coffee',
                'coffee_image'   => 'coffees/drip_coffee.jpg',
                'description'    => 'A simple yet classic brew made by slowly dripping hot water over freshly ground coffee. Its clean taste highlights the bean’s natural flavour profile—smooth, balanced, and perfect for those who enjoy coffee in its purest form.',
                'ingredients'    => 'Ground Coffee, Hot Water',
                'coffee_type'    => 'balanced',
                'lactose'        => 'no',
                'minimum_price'  => 70.00,
                'maximum_price'  => 100.00,
                'rating'         => 2.9,
                'likes'          => 25,
                'favorites'      => 7,
            ],
            [
                'coffee_name'    => 'Japanese Iced Coffee',
                'coffee_image'   => 'coffees/japanese_iced_coffee.jpg',
                'description'    => 'A refreshing fusion of hot brewing and iced cooling, this flash-brew method locks in the coffee’s bright acidity and rich aroma. Poured directly over ice, it offers a crisp, clean flavour that’s both bold and invigorating.',
                'ingredients'    => 'Ground Coffee, Ice, Hot Water',
                'coffee_type'    => 'balanced',
                'lactose'        => 'no',
                'minimum_price'  => 100.00,
                'maximum_price'  => 140.00,
                'rating'         => 3.9,
                'likes'          => 90,
                'favorites'      => 35,
            ],
            [
                'coffee_name'    => 'Macapuno Latte',
                'coffee_image'   => 'coffees/macapuno_latte.jpg',
                'description'    => 'A tropical twist on the classic latte—rich espresso meets creamy steamed milk infused with the sweet, nutty flavour of macapuno coconut. A delightful drink that captures the comforting taste of the Philippines in every sip.',
                'ingredients'    => 'Espresso, Steamed Milk, Macapuno Syrup',
                'coffee_type'    => 'balanced',
                'lactose'        => 'yes',
                'minimum_price'  => 130.00,
                'maximum_price'  => 170.00,
                'rating'         => 4.2,
                'likes'          => 150,
                'favorites'      => 60,
            ],
            [
                'coffee_name'    => 'Coconut Sugar Latte',
                'coffee_image'   => 'coffees/coconut_sugar_latte.jpg',
                'description'    => 'Crafted with natural coconut sugar, this latte offers a gentle caramel sweetness paired with smooth espresso and creamy milk. It’s a comforting, lightly sweet beverage that highlights earthy, tropical undertones.',
                'ingredients'    => 'Espresso, Steamed Milk, Coconut Sugar',
                'coffee_type'    => 'balanced',
                'lactose'        => 'yes',
                'minimum_price'  => 120.00,
                'maximum_price'  => 160.00,
                'rating'         => 3.2,
                'likes'          => 70,
                'favorites'      => 25,
            ],
            [
                'coffee_name'    => 'Sweet Corn Latte',
                'coffee_image'   => 'coffees/sweet_corn_latte.jpg',
                'description'    => 'An inventive blend that combines the smooth texture of steamed milk with the comforting sweetness of corn syrup. Each sip reveals a creamy, nostalgic flavour reminiscent of local Filipino desserts with a hint of espresso boldness.',
                'ingredients'    => 'Espresso, Steamed Milk, Corn Syrup',
                'coffee_type'    => 'balanced',
                'lactose'        => 'yes',
                'minimum_price'  => 120.00,
                'maximum_price'  => 160.00,
                'rating'         => 2.8,
                'likes'          => 34,
                'favorites'      => 12,
            ],
            [
                'coffee_name'    => 'Muscovado Latte',
                'coffee_image'   => 'coffees/muscovado_latte.jpg',
                'description'    => 'Rich espresso combined with steamed milk and muscovado sugar for a deep, molasses-like sweetness. This latte delivers a rustic charm, bringing warmth and a satisfying caramel finish to each sip.',
                'ingredients'    => 'Espresso, Steamed Milk, Muscovado Sugar',
                'coffee_type'    => 'balanced',
                'lactose'        => 'yes',
                'minimum_price'  => 120.00,
                'maximum_price'  => 160.00,
                'rating'         => 4.0,
                'likes'          => 100,
                'favorites'      => 40,
            ],
            [
                'coffee_name'    => 'Matcha Pandan Latte',
                'coffee_image'   => 'coffees/matcha_pandan_latte.jpg',
                'description'    => 'A unique fusion of earthy matcha and fragrant pandan blended into a creamy latte base. This vibrant green drink balances the grassy notes of matcha with the tropical sweetness of pandan, creating a beautifully smooth harmony.',
                'ingredients'    => 'Espresso, Steamed Milk, Matcha, Pandan Syrup',
                'coffee_type'    => 'balanced',
                'lactose'        => 'yes',
                'minimum_price'  => 140.00,
                'maximum_price'  => 180.00,
                'rating'         => 4.5,
                'likes'          => 210,
                'favorites'      => 80,
            ],
            [
                'coffee_name'    => 'Ube Latte',
                'coffee_image'   => 'coffees/ube_latte.jpg',
                'description'    => 'A colourful and creamy blend of espresso, milk, and sweet ube syrup. This Filipino-inspired latte offers a velvety texture and a nutty, vanilla-like flavour that’s both comforting and visually delightful.',
                'ingredients'    => 'Espresso, Steamed Milk, Ube Syrup',
                'coffee_type'    => 'balanced',
                'lactose'        => 'yes',
                'minimum_price'  => 130.00,
                'maximum_price'  => 170.00,
                'rating'         => 4.7,
                'likes'          => 240,
                'favorites'      => 92,
            ],
            [
                'coffee_name'    => 'Toasted Coconut Mocha',
                'coffee_image'   => 'coffees/toasted_coconut_mocha.jpg',
                'description'    => 'This mocha takes tropical indulgence to the next level—rich chocolate and espresso meet the nutty aroma of toasted coconut. It’s a luxurious treat for those who love a perfect balance of sweetness and roasted depth.',
                'ingredients'    => 'Espresso, Steamed Milk, Toasted Coconut Syrup',
                'coffee_type'    => 'balanced',
                'lactose'        => 'yes',
                'minimum_price'  => 130.00,
                'maximum_price'  => 170.00,
                'rating'         => 3.7,
                'likes'          => 95,
                'favorites'      => 36,
            ],
            [
                'coffee_name'    => 'Iced Honey Oatmilk Latte',
                'coffee_image'   => 'coffees/iced_honey_oatmilk_latte.jpg',
                'description'    => 'A smooth and refreshing dairy-free option featuring espresso, natural honey, and creamy oat milk served over ice. Lightly sweet with a nutty finish, it’s a wholesome way to enjoy a chilled coffee boost.',
                'ingredients'    => 'Espresso, Honey, Oatmilk, Ice',
                'coffee_type'    => 'balanced',
                'lactose'        => 'yes',
                'minimum_price'  => 140.00,
                'maximum_price'  => 180.00,
                'rating'         => 4.1,
                'likes'          => 120,
                'favorites'      => 50,
            ],
            [
                'coffee_name'    => 'Caramel Frappe',
                'coffee_image'   => 'coffees/caramel_frappe.jpg',
                'description'    => 'A delightful icy blend of espresso, milk, and smooth caramel syrup, topped with a drizzle of golden caramel. This indulgent frappe offers a sweet, buttery taste and a creamy texture that makes it the perfect dessert in a cup.',
                'ingredients'    => 'Espresso, Milk, Caramel Syrup, Ice',
                'coffee_type'    => 'sweet',
                'lactose'        => 'yes',
                'minimum_price'  => 150.00,
                'maximum_price'  => 190.00,
                'rating'         => 4.8,
                'likes'          => 240,
                'favorites'      => 130,
            ],
            [
                'coffee_name'    => 'White Chocolate Mocha',
                'coffee_image'   => 'coffees/white_chocolate_mocha.jpg',
                'description'    => 'Velvety espresso blended with steamed milk and rich white chocolate sauce. Each sip delivers a silky sweetness balanced by bold coffee notes, making it a luxurious treat for those with a soft spot for smooth and creamy flavours.',
                'ingredients'    => 'Espresso, White Chocolate, Steamed Milk',
                'coffee_type'    => 'sweet',
                'lactose'        => 'yes',
                'minimum_price'  => 150.00,
                'maximum_price'  => 190.00,
                'rating'         => 4.6,
                'likes'          => 250,
                'favorites'      => 100,
            ],
            [
                'coffee_name'    => 'Salted Caramel Latte',
                'coffee_image'   => 'coffees/salted_caramel_latte.jpg',
                'description'    => 'A luxurious combination of creamy milk, caramel syrup, and a touch of sea salt that enhances the sweetness with a subtle savoury note. The result is a rich and balanced latte that’s irresistibly smooth and satisfying.',
                'ingredients'    => 'Espresso, Steamed Milk, Salted Caramel Syrup',
                'coffee_type'    => 'sweet',
                'lactose'        => 'yes',
                'minimum_price'  => 140.00,
                'maximum_price'  => 180.00,
                'rating'         => 4.2,
                'likes'          => 190,
                'favorites'      => 75,
            ],
            [
                'coffee_name'    => 'Iced Caramel Macchiato',
                'coffee_image'   => 'coffees/iced_caramel_macchiato.jpg',
                'description'    => 'A chilled masterpiece layered with milk, espresso, and a swirl of caramel drizzle. This iced delight delivers both sweetness and boldness, creating a visually stunning and refreshingly rich coffee experience.',
                'ingredients'    => 'Espresso, Milk, Caramel Syrup, Ice',
                'coffee_type'    => 'sweet',
                'lactose'        => 'yes',
                'minimum_price'  => 150.00,
                'maximum_price'  => 190.00,
                'rating'         => 3.3,
                'likes'          => 72,
                'favorites'      => 28,
            ],
            [
                'coffee_name'    => 'Chocolate Frappe',
                'coffee_image'   => 'coffees/chocolate_frappe.jpg',
                'description'    => 'A rich and creamy blend of espresso, milk, and chocolate syrup crushed together with ice. The perfect pick-me-up for chocolate lovers, offering a smooth texture and indulgent sweetness with every sip.',
                'ingredients'    => 'Espresso, Milk, Chocolate Syrup, Ice',
                'coffee_type'    => 'sweet',
                'lactose'        => 'yes',
                'minimum_price'  => 150.00,
                'maximum_price'  => 190.00,
                'rating'         => 4.4,
                'likes'          => 200,
                'favorites'      => 80,
            ],
            [
                'coffee_name'    => 'Chocolate Frappuccino',
                'coffee_image'   => 'coffees/chocolate_frappuccino.jpg',
                'description'    => 'A café favourite that blends espresso, chocolate, and milk into a smooth, icy delight. Finished with whipped cream, this drink delivers a decadent mix of cool sweetness and robust coffee flavour.',
                'ingredients'    => 'Espresso, Milk, Chocolate Syrup, Whipped Cream',
                'coffee_type'    => 'sweet',
                'lactose'        => 'yes',
                'minimum_price'  => 160.00,
                'maximum_price'  => 200.00,
                'rating'         => 4.9,
                'likes'          => 290,
                'favorites'      => 150,
            ],
            [
                'coffee_name'    => 'Mocha Frappuccino',
                'coffee_image'   => 'coffees/mocha_frappuccino.jpg',
                'description'    => 'An irresistible blend of coffee, milk, and chocolate that’s whipped into an icy, creamy beverage. Topped with whipped cream, it’s a refreshing mix of sweetness and bold espresso flavour for true mocha fans.',
                'ingredients'    => 'Espresso, Milk, Chocolate, Ice',
                'coffee_type'    => 'sweet',
                'lactose'        => 'yes',
                'minimum_price'  => 160.00,
                'maximum_price'  => 200.00,
                'rating'         => 4.7,
                'likes'          => 280,
                'favorites'      => 120,
            ],
            [
                'coffee_name'    => 'Java Chip Frappuccino',
                'coffee_image'   => 'coffees/java_chip_frappuccino.jpg',
                'description'    => 'A chocolate lover’s dream — espresso, milk, and chocolate syrup blended with crunchy choco chips for a delightful texture. Every sip bursts with rich mocha flavour and an indulgent, frosty sweetness.',
                'ingredients'    => 'Espresso, Milk, Chocolate Syrup, Choco Chips',
                'coffee_type'    => 'sweet',
                'lactose'        => 'yes',
                'minimum_price'  => 160.00,
                'maximum_price'  => 200.00,
                'rating'         => 4.8,
                'likes'          => 330,
                'favorites'      => 150,
            ],
            [
                'coffee_name'    => 'Maple Latte',
                'coffee_image'   => 'coffees/maple_latte.jpg',
                'description'    => 'A cozy and aromatic drink made with espresso, steamed milk, and pure maple syrup. Its subtle sweetness and smooth texture create a warm, comforting flavour reminiscent of breakfast mornings and fall days.',
                'ingredients'    => 'Espresso, Steamed Milk, Maple Syrup',
                'coffee_type'    => 'sweet',
                'lactose'        => 'yes',
                'minimum_price'  => 130.00,
                'maximum_price'  => 170.00,
                'rating'         => 3.8,
                'likes'          => 88,
                'favorites'      => 33,
            ],
            [
                'coffee_name'    => 'Dulce de Leche Latte',
                'coffee_image'   => 'coffees/dulce_de_leche_latte.jpg',
                'description'    => 'A sweet and creamy delight featuring espresso blended with steamed milk and luscious dulce de leche. This Latin-inspired latte delivers a buttery caramel richness that melts beautifully on your palate.',
                'ingredients'    => 'Espresso, Steamed Milk, Dulce de Leche',
                'coffee_type'    => 'sweet',
                'lactose'        => 'yes',
                'minimum_price'  => 140.00,
                'maximum_price'  => 180.00,
                'rating'         => 4.0,
                'likes'          => 110,
                'favorites'      => 40,
            ],
            [
                'coffee_name'    => 'Raspberry Mocha',
                'coffee_image'   => 'coffees/raspberry_mocha.jpg',
                'description'    => 'A playful combination of espresso, milk, chocolate syrup, and raspberry flavouring. The tartness of raspberry perfectly complements the deep cocoa tones, creating a vibrant and velvety-smooth mocha experience.',
                'ingredients'    => 'Espresso, Milk, Chocolate Syrup, Raspberry Syrup',
                'coffee_type'    => 'sweet',
                'lactose'        => 'yes',
                'minimum_price'  => 130.00,
                'maximum_price'  => 170.00,
                'rating'         => 2.4,
                'likes'          => 18,
                'favorites'      => 5,
            ],
            [
                'coffee_name'    => 'Cinnamon Dolce Latte',
                'coffee_image'   => 'coffees/cinnamon_dolce_latte.jpg',
                'description'    => 'Warm and fragrant, this latte blends espresso with steamed milk and sweet cinnamon dolce syrup. The aromatic spice and creamy texture make it a cozy choice for anyone craving a comforting coffee treat.',
                'ingredients'    => 'Espresso, Steamed Milk, Cinnamon Syrup',
                'coffee_type'    => 'sweet',
                'lactose'        => 'yes',
                'minimum_price'  => 130.00,
                'maximum_price'  => 170.00,
                'rating'         => 3.6,
                'likes'          => 95,
                'favorites'      => 34,
            ],
        ];

        foreach ($coffees as $coffee) {
            DB::table('coffees')->updateOrInsert(
                ['coffee_name' => $coffee['coffee_name']],
                $coffee + [
                    'created_at' => now(),
                    'updated_at' => now(),
                ]
            );
        }
    }
}
