<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CoffeeSeeder extends Seeder
{
    public function run(): void
    {
        $coffees = [
            ['coffee_name'=>'Espresso','coffee_image'=>'coffees/espresso.jpg','description'=>'Strong concentrated shot of coffee.','ingredients'=>'Water, Coffee Beans','coffee_type'=>'arabica','serving_temp'=>'hot','lactose'=>false,'nuts'=>false,'price'=>95.00,'rating'=>4.50,'likes'=>120,'favorites'=>25],
            ['coffee_name'=>'Cappuccino','coffee_image'=>'coffees/cappuccino.jpg','description'=>'Espresso with steamed milk and foam.','ingredients'=>'Espresso, Milk, Foam','coffee_type'=>'arabica','serving_temp'=>'both','lactose'=>true,'nuts'=>false,'price'=>135.00,'rating'=>4.75,'likes'=>200,'favorites'=>60],
            ['coffee_name'=>'Latte','coffee_image'=>'coffees/latte.png','description'=>'Creamy espresso drink with steamed milk.','ingredients'=>'Espresso, Milk','coffee_type'=>'arabica','serving_temp'=>'both','lactose'=>true,'nuts'=>false,'price'=>140.00,'rating'=>4.60,'likes'=>180,'favorites'=>40],
            ['coffee_name'=>'Americano','coffee_image'=>'coffees/americano.jpg','description'=>'Espresso diluted with hot water.','ingredients'=>'Espresso, Water','coffee_type'=>'arabica','serving_temp'=>'both','lactose'=>false,'nuts'=>false,'price'=>105.00,'rating'=>4.40,'likes'=>110,'favorites'=>50],
            ['coffee_name'=>'Flat White','coffee_image'=>'coffees/flat_white.jpg','description'=>'Espresso with micro‑foamed milk.','ingredients'=>'Espresso, Milk','coffee_type'=>'arabica','serving_temp'=>'hot','lactose'=>true,'nuts'=>false,'price'=>120.00,'rating'=>4.30,'likes'=>150,'favorites'=>60],
            ['coffee_name'=>'Mocha','coffee_image'=>'coffees/mocha.jpg','description'=>'Chocolate flavored espresso with milk.','ingredients'=>'Espresso, Milk, Chocolate Syrup','coffee_type'=>'arabica','serving_temp'=>'both','lactose'=>true,'nuts'=>false,'price'=>150.00,'rating'=>4.80,'likes'=>290,'favorites'=>110],
            ['coffee_name'=>'Cold Brew','coffee_image'=>'coffees/coldbrew.png','description'=>'Coffee steeped in cold water for hours.','ingredients'=>'Cold Water, Coffee Beans','coffee_type'=>'robusta','serving_temp'=>'iced','lactose'=>false,'nuts'=>false,'price'=>160.00,'rating'=>4.30,'likes'=>95,'favorites'=>30],
            ['coffee_name'=>'Iced Latte','coffee_image'=>'coffees/latte.png','description'=>'Chilled latte over ice.','ingredients'=>'Espresso, Milk, Ice','coffee_type'=>'arabica','serving_temp'=>'iced','lactose'=>true,'nuts'=>false,'price'=>145.00,'rating'=>4.55,'likes'=>210,'favorites'=>70],
            ['coffee_name'=>'Iced Americano','coffee_image'=>'coffees/americano.jpg','description'=>'Cold water and espresso over ice.','ingredients'=>'Espresso, Water, Ice','coffee_type'=>'arabica','serving_temp'=>'iced','lactose'=>false,'nuts'=>false,'price'=>100.00,'rating'=>4.45,'likes'=>130,'favorites'=>40],
            ['coffee_name'=>'Macchiato','coffee_image'=>'coffees/macchiato.jpg','description'=>'Espresso “stained” with foam.','ingredients'=>'Espresso, Foam','coffee_type'=>'arabica','serving_temp'=>'hot','lactose'=>true,'nuts'=>false,'price'=>110.00,'rating'=>4.35,'likes'=>85,'favorites'=>20],
            ['coffee_name'=>'Affogato','coffee_image'=>'coffees/affogato.jpg','description'=>'Espresso poured over ice cream.','ingredients'=>'Espresso, Ice Cream','coffee_type'=>'arabica','serving_temp'=>'both','lactose'=>true,'nuts'=>false,'price'=>155.00,'rating'=>4.65,'likes'=>90,'favorites'=>30],
            ['coffee_name'=>'Ristretto','coffee_image'=>'coffees/ristretto.jpg','description'=>'Short concentrated espresso shot.','ingredients'=>'Water, Coffee Beans','coffee_type'=>'arabica','serving_temp'=>'hot','lactose'=>false,'nuts'=>false,'price'=>90.00,'rating'=>4.70,'likes'=>220,'favorites'=>90],
            ['coffee_name'=>'Long Black','coffee_image'=>'coffees/long_black.jpg','description'=>'Double espresso over hot water.','ingredients'=>'Espresso, Hot Water','coffee_type'=>'arabica','serving_temp'=>'hot','lactose'=>false,'nuts'=>false,'price'=>100.00,'rating'=>3.10,'likes'=>55,'favorites'=>20],
            ['coffee_name'=>'Kapeng Barako','coffee_image'=>'coffees/kapeng_barako.png','description'=>'Filipino Liberica coffee, strong and smoky.','ingredients'=>'Liberica Beans, Water','coffee_type'=>'liberica','serving_temp'=>'hot','lactose'=>false,'nuts'=>false,'price'=>80.00,'rating'=>4.90,'likes'=>310,'favorites'=>120],
            ['coffee_name'=>'Bulletproof Coffee','coffee_image'=>'coffees/bulletproof_coffee.jpg','description'=>'Coffee blended with butter and oil for energy boost.','ingredients'=>'Coffee, Butter, MCT Oil','coffee_type'=>'robusta','serving_temp'=>'hot','lactose'=>true,'nuts'=>false,'price'=>150.00,'rating'=>2.50,'likes'=>20,'favorites'=>7],
            ['coffee_name'=>'Cortado','coffee_image'=>'coffees/cortado.jpg','description'=>'Espresso cut with warm milk.','ingredients'=>'Espresso, Milk','coffee_type'=>'arabica','serving_temp'=>'hot','lactose'=>true,'nuts'=>false,'price'=>95.00,'rating'=>2.70,'likes'=>30,'favorites'=>10],
            ['coffee_name'=>'Mocha Frappuccino','coffee_image'=>'coffees/mocha_frappuccino.jpg','description'=>'Iced blend of coffee, chocolate, and milk.','ingredients'=>'Espresso, Milk, Chocolate, Ice','coffee_type'=>'arabica','serving_temp'=>'iced','lactose'=>true,'nuts'=>false,'price'=>165.00,'rating'=>4.70,'likes'=>280,'favorites'=>120],
            ['coffee_name'=>'Java Chip Frappuccino','coffee_image'=>'coffees/java_chip_frappuccino.jpg','description'=>'Iced chocolate‑coffee with chips.','ingredients'=>'Espresso, Milk, Chocolate, Ice, Chips','coffee_type'=>'arabica','serving_temp'=>'iced','lactose'=>true,'nuts'=>false,'price'=>170.00,'rating'=>4.80,'likes'=>330,'favorites'=>150],
            ['coffee_name'=>'Caramel Frappe','coffee_image'=>'coffees/caramel_frappe.jpg','description'=>'Sweet iced coffee with caramel syrup.','ingredients'=>'Espresso, Milk, Caramel, Ice','coffee_type'=>'arabica','serving_temp'=>'iced','lactose'=>true,'nuts'=>false,'price'=>165.00,'rating'=>4.80,'likes'=>240,'favorites'=>130],
            ['coffee_name'=>'Iced Matcha Latte','coffee_image'=>'coffees/icedmatcha.webp','description'=>'Matcha green tea latte over ice.','ingredients'=>'Matcha, Milk, Ice','coffee_type'=>'arabica','serving_temp'=>'iced','lactose'=>true,'nuts'=>false,'price'=>150.00,'rating'=>4.85,'likes'=>200,'favorites'=>80],
            ['coffee_name'=>'Vanilla Latte','coffee_image'=>'coffees/vanilla_latte.jpg','description'=>'Latte flavored with vanilla syrup.','ingredients'=>'Espresso, Milk, Vanilla Syrup','coffee_type'=>'arabica','serving_temp'=>'both','lactose'=>true,'nuts'=>false,'price'=>150.00,'rating'=>4.75,'likes'=>270,'favorites'=>100],
            ['coffee_name'=>'Brown Sugar Latte','coffee_image'=>'coffees/brown_sugar_latte.jpg','description'=>'Latte with caramelized brown sugar.','ingredients'=>'Espresso, Milk, Brown Sugar Syrup','coffee_type'=>'arabica','serving_temp'=>'both','lactose'=>true,'nuts'=>false,'price'=>155.00,'rating'=>4.70,'likes'=>240,'favorites'=>95],
            ['coffee_name'=>'Cafe au Lait','coffee_image'=>'coffees/cafe_au_lait.jpg','description'=>'Brewed coffee with steamed milk.','ingredients'=>'Coffee, Milk','coffee_type'=>'arabica','serving_temp'=>'both','lactose'=>true,'nuts'=>false,'price'=>130.00,'rating'=>3.00,'likes'=>60,'favorites'=>22],
            ['coffee_name'=>'Cafe Latte','coffee_image'=>'coffees/cafe_latte.jpg','description'=>'Mellow espresso and milk coffee.','ingredients'=>'Espresso, Milk','coffee_type'=>'arabica','serving_temp'=>'both','lactose'=>true,'nuts'=>false,'price'=>145.00,'rating'=>4.60,'likes'=>200,'favorites'=>90],
            ['coffee_name'=>'Drip Coffee','coffee_image'=>'coffees/drip_coffee.jpg','description'=>'Simple brewed drip coffee.','ingredients'=>'Ground Coffee, Water','coffee_type'=>'arabica','serving_temp'=>'hot','lactose'=>false,'nuts'=>false,'price'=>80.00,'rating'=>2.90,'likes'=>25,'favorites'=>7],
            ['coffee_name'=>'Japanese Iced Coffee','coffee_image'=>'coffees/japanese_iced_coffee.jpg','description'=>'Flash‑brewed coffee poured over ice for crisp flavour.','ingredients'=>'Ground Coffee, Water, Ice','coffee_type'=>'arabica','serving_temp'=>'iced','lactose'=>false,'nuts'=>false,'price'=>140.00,'rating'=>3.90,'likes'=>90,'favorites'=>35],
            ['coffee_name'=>'Ube Latte','coffee_image'=>'coffees/ube_latte.jpg','description'=>'Latte with Filipino ube syrup.','ingredients'=>'Espresso, Milk, Ube Syrup','coffee_type'=>'arabica','serving_temp'=>'both','lactose'=>true,'nuts'=>false,'price'=>155.00,'rating'=>4.70,'likes'=>240,'favorites'=>92],
            ['coffee_name'=>'Muscovado Latte','coffee_image'=>'coffees/muscovado_latte.jpg','description'=>'Latte sweetened with muscovado sugar.','ingredients'=>'Espresso, Milk, Muscovado Sugar','coffee_type'=>'arabica','serving_temp'=>'both','lactose'=>true,'nuts'=>false,'price'=>150.00,'rating'=>4.00,'likes'=>100,'favorites'=>40],
            ['coffee_name'=>'Sweet Corn Latte','coffee_image'=>'coffees/sweet_corn_latte.jpg','description'=>'Latte with sweet corn syrup twist.','ingredients'=>'Espresso, Milk, Corn Syrup','coffee_type'=>'arabica','serving_temp'=>'both','lactose'=>true,'nuts'=>false,'price'=>150.00,'rating'=>2.80,'likes'=>34,'favorites'=>12],
            ['coffee_name'=>'Toasted Coconut Mocha','coffee_image'=>'coffees/toasted_coconut_mocha.jpg','description'=>'Mocha blended with toasted coconut flavor.','ingredients'=>'Espresso, Milk, Coconut Syrup, Chocolate','coffee_type'=>'arabica','serving_temp'=>'both','lactose'=>true,'nuts'=>false,'price'=>155.00,'rating'=>3.70,'likes'=>95,'favorites'=>36],
            ['coffee_name'=>'Salted Caramel Latte','coffee_image'=>'coffees/salted_caramel_latte.jpg','description'=>'Latte with salted caramel syrup.','ingredients'=>'Espresso, Milk, Caramel Syrup','coffee_type'=>'arabica','serving_temp'=>'both','lactose'=>true,'nuts'=>false,'price'=>150.00,'rating'=>4.20,'likes'=>190,'favorites'=>75],
            ['coffee_name'=>'Iced Caramel Macchiato','coffee_image'=>'coffees/iced_caramel_macchiato.jpg','description'=>'Layered iced espresso with milk and caramel drizzle.','ingredients'=>'Espresso, Milk, Caramel Syrup, Ice','coffee_type'=>'arabica','serving_temp'=>'iced','lactose'=>true,'nuts'=>false,'price'=>155.00,'rating'=>3.30,'likes'=>72,'favorites'=>28],
            ['coffee_name'=>'Chocolate Frappe','coffee_image'=>'coffees/chocolate_frappe.jpg','description'=>'Iced chocolate‑coffee blended drink.','ingredients'=>'Espresso, Milk, Chocolate, Ice','coffee_type'=>'arabica','serving_temp'=>'iced','lactose'=>true,'nuts'=>false,'price'=>165.00,'rating'=>4.40,'likes'=>200,'favorites'=>80],
            ['coffee_name'=>'Red Eye Coffee','coffee_image'=>'coffees/red_eye_coffee.jpg','description'=>'Drip coffee with a shot of espresso for extra kick.','ingredients'=>'Drip Coffee, Espresso','coffee_type'=>'arabica','serving_temp'=>'hot','lactose'=>false,'nuts'=>false,'price'=>100.00,'rating'=>2.90,'likes'=>28,'favorites'=>8],
            ['coffee_name'=>'Vienna Coffee','coffee_image'=>'coffees/vienna_coffee.jpg','description'=>'Espresso topped with whipped cream.','ingredients'=>'Espresso, Whipped Cream','coffee_type'=>'arabica','serving_temp'=>'hot','lactose'=>true,'nuts'=>false,'price'=>145.00,'rating'=>3.50,'likes'=>80,'favorites'=>30],
            ['coffee_name'=>'Espresso con Panna','coffee_image'=>'coffees/espresso_con_panna.jpg','description'=>'Espresso with a dollop of whipped cream.','ingredients'=>'Espresso, Whipped Cream','coffee_type'=>'arabica','serving_temp'=>'hot','lactose'=>true,'nuts'=>false,'price'=>120.00,'rating'=>2.60,'likes'=>24,'favorites'=>9],
            ['coffee_name'=>'Cinnamon Dolce Latte','coffee_image'=>'coffees/cinnamon_dolce_latte.jpg','description'=>'Latte flavored with cinnamon syrup.','ingredients'=>'Espresso, Milk, Cinnamon Syrup','coffee_type'=>'arabica','serving_temp'=>'both','lactose'=>true,'nuts'=>false,'price'=>150.00,'rating'=>3.60,'likes'=>95,'favorites'=>34],
            ['coffee_name'=>'Iced Honey Oatmilk Latte','coffee_image'=>'coffees/iced_honey_oatmilk_latte.jpg','description'=>'Dairy‑free iced latte with honey and oat milk.','ingredients'=>'Espresso, Oat Milk, Honey, Ice','coffee_type'=>'arabica','serving_temp'=>'iced','lactose'=>false,'nuts'=>false,'price'=>155.00,'rating'=>4.10,'likes'=>120,'favorites'=>50],
            ['coffee_name'=>'Pistachio Latte','coffee_image'=>'coffees/piccolo_latte.jpg','description'=>'Latte infused with pistachio syrup.','ingredients'=>'Espresso, Milk, Pistachio Syrup','coffee_type'=>'arabica','serving_temp'=>'both','lactose'=>true,'nuts'=>true,'price'=>160.00,'rating'=>4.50,'likes'=>130,'favorites'=>55],
            ['coffee_name'=>'Hazelnut Mocha','coffee_image'=>'coffees/hazelnut_latte.jpg','description'=>'Mocha with hazelnut flavor and chocolate.','ingredients'=>'Espresso, Milk, Hazelnut Syrup, Chocolate','coffee_type'=>'arabica','serving_temp'=>'both','lactose'=>true,'nuts'=>true,'price'=>155.00,'rating'=>4.55,'likes'=>140,'favorites'=>65],
            ['coffee_name'=>'Irish Coffee','coffee_image'=>'coffees/latte.png','description'=>'Hot coffee with cream (non‑alcoholic version).','ingredients'=>'Coffee, Cream','coffee_type'=>'arabica','serving_temp'=>'hot','lactose'=>true,'nuts'=>false,'price'=>130.00,'rating'=>4.20,'likes'=>95,'favorites'=>30],
            ['coffee_name'=>'Vienna Iced Latte','coffee_image'=>'coffees/vienna_coffee.jpg','description'=>'Iced latte topped with whipped cream.','ingredients'=>'Espresso, Milk, Ice, Whipped Cream','coffee_type'=>'arabica','serving_temp'=>'iced','lactose'=>true,'nuts'=>false,'price'=>150.00,'rating'=>4.25,'likes'=>110,'favorites'=>45],
            ['coffee_name'=>'Maple Latte','coffee_image'=>'coffees/maple_latte.jpg','description'=>'Latte with maple syrup flavor.','ingredients'=>'Espresso, Milk, Maple Syrup','coffee_type'=>'arabica','serving_temp'=>'both','lactose'=>true,'nuts'=>false,'price'=>150.00,'rating'=>3.80,'likes'=>88,'favorites'=>33],
            ['coffee_name'=>'Dulce de Leche Latte','coffee_image'=>'coffees/dulce_de_leche_latte.jpg','description'=>'Latte sweetened with dulce de leche.','ingredients'=>'Espresso, Milk, Dulce de Leche','coffee_type'=>'arabica','serving_temp'=>'both','lactose'=>true,'nuts'=>false,'price'=>155.00,'rating'=>4.00,'likes'=>110,'favorites'=>40],
            ['coffee_name'=>'Raspberry Mocha','coffee_image'=>'coffees/raspberry_mocha.jpg','description'=>'Chocolate‑coffee with raspberry flavor.','ingredients'=>'Espresso, Milk, Chocolate Syrup, Raspberry Syrup','coffee_type'=>'arabica','serving_temp'=>'both','lactose'=>true,'nuts'=>false,'price'=>155.00,'rating'=>2.40,'likes'=>18,'favorites'=>5],
        ];

        foreach ($coffees as $coffee) {
            DB::table('coffees')->updateOrInsert(
                ['coffee_name' => $coffee['coffee_name']],
                array_merge($coffee, [
                    'created_at' => now(),
                    'updated_at' => now(),
                ])
            );
        }
    }
}
